# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1a0a26e4e12bd76ad42ded4215c21e9644d01c12e2f275e979391881d78880ae470ccc052da655bfed06939ed716ee276590704d94e00b51b865d87410cfe47

test:
  secret_key_base: a60e920ed2ef05f797937c598903530d4d5fa12adb4a89532015df43e85ff5f08037b5fd0ff9585ea2a57ea60443c32576f4d2755ff8dbbd7c2a36615146726b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
